flowchart LR

  infbr[Information Brute] --> traitement
  subgraph traitement [Traitement]
  direction LR
  Perception --> Représentation
  end
  traitement --> codage
  subgraph codage [Codage]
  direction LR
  Numérisation --> Cryptographie
  end
  codage --> infnet[Information Exploitable]
